language: java
os:
  - linux
  - mac
jdk:
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
cache:
  directories: $HOME/.m2
install:
addons:
  homebrew:
    packages: scrcpy
  chrome: stable
  apt:
    sources: google-chrome
    packages: google-chrome-stable
script:
 - mvn install -Dchromeoptions.args=--no-sandbox