name: Java CI
on: [push, pull_request]
jobs:
  build:
    runs-on: x86
    strategy:
      fail-fast: false
      matrix:
        java_version: [10, 11, 12, 13]
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK $
        uses: actions/setup-java@v1
        with:
          java-version: $
      - name: Make Maven Wrapper executable
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw package --file pom.xml
